# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amutheezan Sivagnanam
title: PhD Student & Graduate Research Assistant
email: asivagnanam@uh.edu
website: www.amutheezan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: amux93
github_username:  amutheezan
stackoverflow_username: amutheezan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amutheez
linkedin_username: amutheezansivagnanam
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: website
  icon: fas fa-globe
  url: https://www.amutheezan.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/display_picture.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am currently in my 2nd year of PhD, I joined in the Resilient Networks and Systems (RNS) Lab as a Ph.D. Student in Fall 2019.
  My research interest is in Machine Learning and Data Mining. 
  
content:
  - title: Work Experience # Title for the section
    content:
      - layout: left
        title: University of Houston
        link: https://www.uh.edu/
        sub_title: Graduate Research Assistant
        caption: September 2019 - Present

    layout: list # Type of content section (list/text)
      - layout: left
        title: Millennium Information Technologies (Pvt) Limited
        link: https://www.lseg.com/markets-products-and-services/technology/lseg-technology
        sub_title: Software Engineer
        caption: January 2018 - July 2019
        description: | # this will include new lines to allow paragraphs
          Writing application software in the Object-Oriented manner.
          
          Practicing agile development practices.
          
          Working experience with languages such as Java, Python, and C++.
          
          Introduce Unit Testing for Libraries in Post Trade C++ Code.
          
          Worked on Making changes in DB and Tested with BDD based Testing.
          
          Completed the Code Integration works related to Back-End Regression.
          
          Updated automatic updates to auto-generated codes based on Database changes using Integration Plans.
          
          Participated in Code Integration and Code Deployment Plans.
          
          Participated in professional training programs conducted by Millennium IT Software and Post Trade Team.
          
          Worked on Front-End Development for both Product and Solution which consists of Enhancement, Bug Fixing, Merging and Introducing new features.

    layout: list # Type of content section (list/text)
    - layout: left
      title: WSO2 Lanka (Pvt) Limited
      link: https://wso2.com/about/
      sub_title: Software Engieering Intern
      caption: July 2016 - December 2016
      description: |
         Alerting critical issues in the medical industry by evaluating the HL7Message.
         
         Analysis of the Message flow through out the organization. 
         
         Enhancing the Query capabilities for Message with a highly complex combination of attribute.
         


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Houston
        caption: 2019 Fall - Present
        sub_title: Ph.D in Computer and Information Sciences.

    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Moratuwa
        caption: 2014 January - 2018 Januray
        sub_title: B.Sc. in Engineering (Computer Science and Engineering)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
